routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mahasiswa;
use App\TugasAkhir;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    $guards = ['mahasiswa', 'admin', 'kaprodi', 'dosen'];
    foreach ($guards as $guard) {
        if (Auth::guard($guard)->check()) {
            return redirect()->route($guard . '.home');
        }
    }
    return view('welcome');
})->name('home');

Auth::routes();

Route::prefix('mahasiswa')->name('mahasiswa.')->middleware(['auth:mahasiswa'])->group(function () {
    Route::get('/home', 'Mahasiswa\HomeController@index')->name('home');
    Route::resource('/TA', 'Mahasiswa\TAController');
});

Route::prefix('admin')->name('admin.')->middleware(['auth:admin'])->group(function () {
    Route::get('/home', 'Admin\HomeController@index')->name('home');
    Route::prefix('master')->name('master.')->group(function () {
        Route::resource('mahasiswa', 'Admin\MasterMahasiswaController');
        Route::resource('kaprodi', 'Admin\MasterKaprodiController');
        Route::resource('dosen', 'Admin\MasterDosenController');
    });
    Route::prefix('managemen')->name('managemen.')->group(function () {
        Route::resource('mahasiswa', 'Admin\ManagemenMahasiswaController');
        Route::resource('kaprodi', 'Admin\ManagemenKaprodiController');
        Route::resource('dosen', 'Admin\ManagemenDosenController');
    });
});

Route::prefix('kaprodi')->name('kaprodi')->middleware(['auth:kaprodi'])->group(function () {
    Route::get('/home', 'Kaprodi\HomeController@index')->name('home');
    Route::resource('/TA', 'Kaprodi\ListTAController');
});

// Route::group(['middleware' => ['auth:dosen']], function () {
//     Route::get('/home', 'Dosen\DosenController@index')->name('home');
// });

Route::prefix('dosen')->name('dosen.')->middleware(['auth:dosen'])->group(function () {
    Route::get('/home', 'Dosen\HomeController@index')->name('home');
    Route::resource('managemen', 'Dosen\ManagemenJudulController');
});

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <h1 class="text-{{Auth::check() ? 'black' : 'white'}}">SINTAK</h1>
            {{-- <img src="{{ asset('argon') }}/img/brand/blue.png" class="navbar-brand-img" alt="..."> --}}
        </a>
        <!-- User -->
        {{-- <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div> --}}
                    {{-- <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a> --}}
                    {{-- <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>{{ __('Activity') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>{{ __('Support') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul> --}}
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <h1 class="text-{{Auth::check() ? 'black' : 'white'}}">SINTAK</h1>
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                @auth("admin")
                <li class="nav-item">
                        <a class="nav-link" href="#navbar-master" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-master">
                                <i class="ni ni-single-02 text-blue"></i>
                                <span class="nav-link-text">{{ __('Master') }}</span>
                        </a>
                        <div class="collapse" id="navbar-master">
                            <ul class="nav nav-sm flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('admin.master.mahasiswa.index') }}">
                                        <i class="ni ni-planet text-blue"></i> {{ __('Mahasiswa') }}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('admin.master.kaprodi.index') }}">
                                        <i class="ni ni-planet text-blue"></i> {{ __('Kaprodi') }}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('admin.master.dosen.index') }}">
                                        <i class="ni ni-planet text-blue"></i> {{ __('Dosen') }}
                                    </a>
                                </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#navbar-manage-user" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-manage-user">
                        <i class="ni ni-single-02 text-blue"></i>
                        <span class="nav-link-text">{{ __('Managemen User') }}</span>
                    </a>
                    <div class="collapse" id="navbar-manage-user">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('admin.managemen.mahasiswa.index')}}">
                                    {{ __('Mahasiswa') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('admin.managemen.kaprodi.index')}}">
                                    {{ __('Kaprodi') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('admin.managemen.dosen.index')}}">
                                    {{ __('Dosen') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                @endauth
                @auth("mahasiswa")
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('mahasiswa.TA.index') }}">
                        <i class="ni ni-planet text-blue"></i> {{ __('Tugas akhir') }}
                    </a>
                </li>
                @endauth
                @auth("kaprodi")
                {{-- Ngene nggo navbar kaprodi *ngikuti bae style,e kya sg nduwure --}}
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('kaprodiTA.index') }}">
                        <i class="ni ni-planet text-blue"></i> {{ __('List Tugas akhir') }}
                    </a>
                </li>      

                @endauth
                @auth("dosen")
                {{-- Ngene nggo navbar Dosen --}}
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('dosen.managemen.index') }}">
                        <i class="ni ni-planet text-blue"></i> {{ __('Managemen Judul') }}
                    </a>
                </li>
                @endauth
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading -->
            <h6 class="navbar-heading text-muted">Documentation</h6>
            <!-- Navigation -->
            <ul class="navbar-nav mb-md-3">
                <li class="nav-item">
                    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html">
                        <i class="ni ni-spaceship"></i> Getting started
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html">
                        <i class="ni ni-palette"></i> Foundation
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html">
                        <i class="ni ni-ui-04"></i> Components
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>